### ISSUE TITLE
Please document how to run benchmarks

### ISSUE THREAD

**Issue by yurivict** [bluescarni/mppp#133]
Benchmark executables fine, but how to run them? Is there a target to run them?

**Comment by yurivict** [comment]
> Would you like me to add a specific target in the build system for running all the benchmarks?

This would be nice. -)

**Comment by bluescarni** [comment]
There's a PR up now at #135. It's the first time I use these custom CMake target/command bits, hope I did not screw up.

**Comment by yurivict** [comment]
Thank you for adding the target! It works. One thing that could be improved is if printed progress messages, like tests do.

**Comment by bluescarni** [comment]
The progress report on ``make test`` is done by some internal CMake magic, I would need to figure out how to reproduce it when building the ``benchmark`` target in a cross platform way. For the time being I'll go ahead and merge the PR as it is, I'll keep on reading up the CMake docs to understand what's the best way to proceed.

**Comment by yurivict** [comment]
Ah, ok. This sounds good.
