### ISSUE TITLE
clang-cl ICEs on construction of const qualified structured binding

### ISSUE THREAD

**Issue by degski** [bluescarni/mppp#178]
integer.hpp:2841

    const auto [size, asize] = bl_read_size_asize(src);

ICEs `clang-cl` trunk [(Bug filed)](https://bugs.llvm.org/show_bug.cgi?id=41745).

Is not your problem I know [AFAICS, the code is correct and compiles with VC], but the `const` is un-necessary and taking it out:

    auto [size, asize] = bl_read_size_asize(src);

makes no difference whatsoever, but does make that bit of code compile with `clang-cl` again.

**Comment by bluescarni** [comment]
I'd rather not lose the ``const`` qualifier, but it's easy to add an ``ifdef`` to work around the issue on ``clang-cl`` only. Is this the only instance of the problem?

**Comment by degski** [comment]
It's the one triggered by my code [I'll have scan a bit later if you want, it's not said that those cause trouble, this **is** a compiler bug [not a defect in your code], we don't know how or what]. The `const` qualifier makes no difference [in code generation] and it's contained inside a [short] function-body. I don't see why you would prefer the pre-processor. But yes, any work-around is good.

**Comment by bluescarni** [comment]
I just prefer to mark everything as const, unless I need to mutate it, in order to avoid accidentally writing to it. If it's just a single instance of the issue, I prefer the mental overhead of the preprocessor rather than losing the const.

**Comment by degski** [comment]
Okido

**Comment by bluescarni** [comment]
PR up at #179.

**Comment by bluescarni** [comment]
#179 has been merged, closing the issue.
