### ISSUE TITLE
arbitrary-precision integers are capped at 64 bytes?

### ISSUE THREAD

**Issue by yurivict** [bluescarni/mppp#258]
Instantiating the template ```integer``` with size higher than 64 results in this error:
```
static_assert failed due to requirement '70UL > 0U && 70UL <= 64U' "Invalid static size for integer."
```

Why are arbitrary-precision integers capped?

**Comment by bluescarni** [comment]
The idea behind the cap was that with such a large static size one is probably better off with a dynamic integer anyway. For instance, operations such as swapping and moving will be very costly in an integer with a very large static size (whereas when dynamic storage is employed, move/swap boil down to a couple of pointer swaps).

Note that the cap does not affect the bit size of the integer (which is not capped at all), it only affects the size threshold at which storage switches from static to dynamic.

Do you have specific use cases that require very large static size?

**Comment by yurivict** [comment]
I don't have particular use cases, I was just playing with cryptographic algorithms and found this limitation.
Thanks for your explanation!
