### ISSUE TITLE
[BUG] MSVC C++20 compilation errors

### ISSUE THREAD

**Issue by andrewcorrigan** [bluescarni/mppp#291]
**Describe the bug**

I regularly compile with Clang and GCC in C++20 mode and MSVC in C++17 mode without issue. I just tried to also compile MPPP in C++20 mode on MSVC using
```
Microsoft Visual Studio Professional 2019
Version 16.11.5
```
with flags:
```
/std:c++20 /Zc:__cplusplus /permissive- /EHsc
```

Resulting in compilation errors:
```
\mppp\src\detail\mpfr_arb_cleanup.cpp(117,51): error C2127: 'mppp::detail::`anonymous-namespace'::mpfr_tl_cleanup_inst': illegal initialization of 'constinit' entity with a non-constant expression

\mppp\src\integer.cpp(149,45): error C2127: 'mppp::detail::`anonymous-namespace'::mpz_alloc_cache_inst': illegal initialization of 'constinit' entity with a non-constant expression
```

**To Reproduce**
Compile MPPP with MSVC using `/std:c++20`.

**Workaround**

I worked around the errors by modifying the definition of `MPPP_CONSTINIT` as follows, upon which MPPP compiled successfully.

```
// C++20 constinit.
#if defined(__cpp_constinit)

#define MPPP_CONSTINIT //constinit

#else

#define MPPP_CONSTINIT

#endif
```

**Expected behavior**

No compilation errors

**Environment (please complete the following information):**
 - OS: Windows
 - Installation method: Source
 - Version: 0.21

**Comment by bluescarni** [comment]
@andrewcorrigan 0.21 is a bit old, could you try with the latest stable version (0.26) and see if the error persists? With the help of @7ofNine we fixed a few MSVC C++20 issues if I recall correctly.

**Comment by andrewcorrigan** [comment]
I just downloaded the latest version and added the following to the top of CMakeLists.txt:

```
project(mp++ VERSION 0.26 LANGUAGES CXX C)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++20 /Zc:__cplusplus /permissive- /EHsc")
```

 The second error persists.

```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: mp++, Configuration: Debug x64 ------
2>Building Custom Rule C:/Users/developer/Downloads/mppp-0.26/CMakeLists.txt
2>integer.cpp
2>C:\Users\developer\Downloads\mppp-0.26\src\integer.cpp(151,45): error C2127: 'mppp::detail::`anonymous-namespace'::mpz_alloc_cache_inst': illegal initialization of 'constinit' entity with a non-constant expression
```

I updated the workaround in my local copy to the following, since the code works fine with gcc/clang
```
#if defined(__cpp_constinit) && !defined(_MSC_VER)  // XXX https://github.com/bluescarni/mppp/issues/291
```

**Comment by 7ofNine** [comment]
I just tried it with 0.26 and 16.11.5 Preview 1 and get the same error. And I also remember that I got this error already a while ago and at that time blamed it on a MSVC compiler bug and was too lazy to hunt it down. I am still not sure what constinit really means and when to use it. I simply stuck with C++17. I will try it with VS 2022 what it has to say.

**Comment by 7ofNine** [comment]
VS2022 17.1.0 Preview 1 fails the same way

**Comment by bluescarni** [comment]
@andrewcorrigan @7ofNine cheers, thanks for double checking this.

``constinit`` is a tool to ensure that the initialisation of a global variable happens at compile time. I am not sure why MSVC is complaining, I will check again with GCC + Clang in C++20 mode. In any case the fix is simple, we can just undefine ``MPPP_CONSTINIT`` on MSVC.

**Comment by 7ofNine** [comment]
Hi Francesco,
I still tend to think that it is a MSVC bug. constinit is pretty new and probably not that commonly used, yet. I'll have a look for possible error reports and if not successful might have to create one. As you know not the first one triggered by mp++ or piranha/obake.

**Comment by bluescarni** [comment]
> Hi Francesco, I still tend to think that it is a MSVC bug. constinit is pretty new and probably not that commonly used, yet. I'll have a look for possible error reports and if not successful might have to create one. As you know not the first one triggered by mp++ or piranha/obake.

I would tend to agree. Here's a trimmed down version of the offending code in mp++. Both GCC and clang compile it without issues, MSVC chokes:

https://godbolt.org/z/6nx7aW1TP

So I am inclined to go ahead and just disable ``constinit`` on pure MSVC for the moment.

**Comment by bluescarni** [comment]
@andrewcorrigan @7ofNine would you mind trying the PR up at #292 to see if it fixes the issue?

**Comment by 7ofNine** [comment]
Hi Francesco,
I compiled the PR with VS2019 as well as VS2022 set to C++20. Both cases worked fine.
And to be sure the same is true if set to C++17

**Comment by bluescarni** [comment]
@7ofNine cheers, I merged the PR. Closing the issue.

**Comment by andrewcorrigan** [comment]
Sorry for the delay.  Thanks for fixing this!
