### ISSUE TITLE
[[maybe_unused]] ::mp_limb_t br;

### ISSUE THREAD

**Issue by andrewcorrigan** [bluescarni/mppp#299]
I tried compiling from a project that includes `mppp` as a dependency via `obake`. I see that `mppp` suppresses a lot of warnings, but when I set `-Wall` in my project, I encountered the following warning:

```
/mppp/include/mp++/integer.hpp:2699:25: warning: variable 'br' set but not used [-Wunused-but-set-variable]
            ::mp_limb_t br;
                        ^
/mppp/include/mp++/integer.hpp:2715:25: warning: variable 'br' set but not used [-Wunused-but-set-variable]
            ::mp_limb_t br;
                        ^
```

Would it make sense to specify `[[maybe_unused]]` here?
```
            [[maybe_unused]] ::mp_limb_t br;
```

**Comment by bluescarni** [comment]
@andrewcorrigan indeed, that variable is used only for debugging and thus in release builds it is effectively unused.

mp++ at this time must still support C++11, so direct support for ``maybe_unused`` (a C++17 feature) is not possible. The correct way of doing it is to set up a macro in ``config.hpp.in`` that checks the current C++ standard in use, something like this:

```c++
#if MPPP_CPLUSPLUS >= 201703L

#define MPPP_MAYBE_UNUSED [[maybe_unused]]

#else

#define MPPP_MAYBE_UNUSED

#endif
```

In fact there's already a similar piece of code for the ``[[nodiscard]]`` attribute in ``config.hpp.in``, so ``MPPP_MAYBE_UNUSED`` should probably be folded into that.

Would you like to open a PR?

**Comment by andrewcorrigan** [comment]
Will do
