### ISSUE TITLE
warnings on clang-17.0.2

### ISSUE THREAD

**Issue by andrewcorrigan** [bluescarni/mppp#313]
My last PR, [312](https://github.com/bluescarni/mppp/pull/312), fixed an error I was encountering using MSVC.    Unfortunately, this is now triggering warnings on Clang. Would it make sense to add an #if guard and redo my last PR so that we only include the space for compilers that actually require it?   This way, MSVC continues to compile and hopefully we could silence warnings from compilers that consider this deprecated?

```
/third_party/obake/mppp/include/mp++/detail/integer_literals.hpp:410:1: warning: identifier '_z1' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
  410 | MPPP_DECLARE_INTEGRAL_UDL(1)
      | ^
```

**Comment by bluescarni** [comment]
Would it be possible instead to suppress the specific warning with a pragma or compiler flag for MSVC?

``#ifdef``-fing would certainly work, but I would like to avoid code repetition if possible.

**Comment by bluescarni** [comment]
@andrewcorrigan in #314 I restored the original code (i.e., before #312) for the user-defined literals.

I am not seeing any warnings/errors in the CI on MSVC 17.10.

I also think a the original issue might have been solved by MSVC turning this on by default:

https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/preprocessor-experimental-overview.md

So perhaps it would make sense to turn on this flag in the mp++ build system...

In any case, let me know if you are still having issues. I plan on doing a dot release tomorrow, but I can always quickly do another one if we need to iterate on this.

Closing for the time being.

**Comment by andrewcorrigan** [comment]
I'm really sorry I flaked on this.   I'll try out the latest release and report back if there are any issues.

**Comment by bluescarni** [comment]
@andrewcorrigan no worries, let me know how it goes.

**Comment by andrewcorrigan** [comment]
I dug into the Windows CI setup and was able to reproduces the errors using the conforming preprocessor option...

https://github.com/andrewcorrigan/mppp/actions/runs/11838858846/job/32988951135

I'm going to open a PR in case you want top consider incorporating these changes
