### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by degski** [bluescarni/mppp#78]
Hi Francesco, 

Would like to request to add xor-, or- and and-operator overloads for `mppp:integer<>`.

This library looks awesome, thanks for it!

degski

**Comment by bluescarni** [comment]
Thanks! :)

I'll put them on the roadmap for the next version.

**Comment by bluescarni** [comment]
This has been implemented in #86, I just merged it into master. It will be available in the next version of mp++, but if you want to give it a spin from the latest git head I'd love to hear how it goes.

**Comment by degski** [comment]
Thanks, I'll check it out asap...
